[project]
name = "pascal-part-hss"
version = "0.1.0"
description = "Experiments with pascal part hierarcical semantic segmentation."
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "torch>=2.5.0",
    "torchvision>=0.20.0",
]
